version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: testum-app
    restart: unless-stopped

    env_file:
      - .env

    environment:
      APP_PORT: ${APP_PORT}
      APP_SECRET: ${APP_SECRET}

      LDAP_SERVER: ${LDAP_SERVER}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_TIMEOUT: ${LDAP_TIMEOUT}

    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app_data:/app/data
