-- +goose Up
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    `group` VARCHAR(100) NULL,
    mail VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_lecturer BOOLEAN NOT NULL DEFAULT FALSE,
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE users;
