-- +goose Up
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    login TEXT NOT NULL UNIQUE,
    "group" TEXT,
    mail TEXT NOT NULL,
    name TEXT NOT NULL,
    is_lecturer INTEGER NOT NULL DEFAULT 0,
    date_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE users;
